

spring.datasource.url=jdbc:mysql://localhost:3306/msgdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Paris
spring.datasource.username=Charbel
spring.datasource.password=Charbel


app.jwt.secret=5519c8e013ad750150cd5d9e7902c42ca67af9513dff79602220eec4b3b77905
# Mail local (MailHog, GreenMail, etc.)
spring.mail.host=localhost
spring.mail.port=1025